In [57]:
import numpy as np

1. Matrix Operation
Perform the following operations on the given matrices:
A=[[2    -1], [​0    3​]]
B=[[1   ​ 2], [-3      4​]]
a. A+B
b. AB
c. 3A−2B

In [58]:
A = np.array([
        [2,-1],
        [0,3]
    ])
B = np.array([
    [1,2],
    [-3,4]
])
addition_of_matrices = A+B
product = np.dot(A,B)
operation = 3*A - 2*B

print(addition_of_matrices)
print(product)
print(operation)

[[ 3  1]
 [-3  7]]
[[ 5  0]
 [-9 12]]
[[ 4 -7]
 [ 6  1]]


2. Determinants and Inverses  
    Find the determinant of A.
    Determine whether A is invertible. If yes, calculate A^−1.

In [ ]:
determinant = np.linalg.det(A)
print(determinant)
if not determinant.round() == 0:
    print("Inverse is possible A is non singular")
    inverse_of_A = np.linalg.inv(A)
print(inverse_of_A)

6.0
Inverse is possible since determinant != 0
[[0.5        0.16666667]
 [0.         0.33333333]]


3. 

Eigenvalues and Eigenvectors  

    Compute the eigenvalues and eigenvectors of the matrix:
    C=[[4    1], [​−2       1]​]

4. 

In [60]:
C = np.array([
    [4,1],
    [-2,1]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

[2. 3.]
[[ 1.         -0.70710678]
 [ 0.          0.70710678]]


In [61]:
X = np.array([
    [4, 1.5, 100],   
     [6, 2.0, 150]   
])

Y = np.array([20, 30])

# Matrix equation: X * beta = y
# beta = y * X^-1 
#but X is not square so it can't be inverted
# also here number of equations(2 features) is less than number of unknown variables (3) 
# So there exists infinite possible solutions which can't be computed normally
# so we use leaast square which internally computes SVD 

beta = np.linalg.lstsq(X, Y)
print(beta)
print(type(beta))   # lstsq returns a tuple with solution , and other stuff 

# The solution is the first elemnt of the tuple so [0]
beta = beta[0]
print("β =", beta)


#Calculating for unknown vehicle
car3= np.array([
    [8, 3.0, 200]
])

price_car3 = np.dot(car3, beta)

#dot product returns a matrix so [0]
print(f" price of car 3 : {price_car3[0]}")

(array([7.98722045e-03, 9.29907285e-15, 1.99680511e-01]), array([], dtype=float64), np.int32(2), array([1.80438995e+02, 1.38661779e-01]))
<class 'tuple'>
β = [7.98722045e-03 9.29907285e-15 1.99680511e-01]
 price of car 3 : 40.00000000000003
